#!/usr/bin/env bash

set -o errexit

cd $1 && shift

export app_init_pwd=${app_init_pwd:-123456}
export app_name=${app_name:-blog_math}
export app_port=${app_port:-443}

export app_build_version="${app_build_version:-`date +%s`}"
export client_image_name="modoth/blog_math:${app_client_version:-latest}"
export server_image_name="modoth/blog_server:${app_server_version:-latest}"

if [[ -n "$server" ]]; then
    ssh -nNT -L $PWD/docker.sock:/var/run/docker.sock $server &
    ssh_pid=$!
    sleep 1
    trap "kill $ssh_pid || true; rm $PWD/docker.sock" EXIT
    export DOCKER_HOST=unix://$PWD/docker.sock
fi

if [[ -n "$@" ]]; then
    docker-compose $@
    exit
fi
docker pull ${client_image_name} && docker pull ${server_image_name}
docker-compose up -d --build